version: '3.8'
services:
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: eureka-server
    image: cleverjohann/eureka-server:1.0.0
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=false
      - EUREKA_CLIENT_FETCH-REGISTRY=false

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: auth-service
    image: cleverjohann/auth-service:1.0.0
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: inventory-service
    image: cleverjohann/inventory-service:1.0.0
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: order-service
    image: cleverjohann/order-service:1.0.0
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - inventory-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: api-gateway
    image: cleverjohann/api-gateway:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - auth-service
      - order-service
      - inventory-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka